In [1]:
import pandas as pd
import numpy as np
import random
from sklearn import metrics
from sklearn.metrics import (roc_auc_score, precision_score, average_precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error, roc_curve, auc, classification_report,auc,confusion_matrix,matthews_corrcoef)
from sklearn import logger
from sklearn.datasets import make_blobs,make_multilabel_classification
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import KernelCenterer,LabelEncoder, MinMaxScaler, Normalizer, QuantileTransformer, RobustScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, StandardScaler
from sklearn.manifold import TSNE
import time
from sklearn.metrics import confusion_matrix,classification_report
import scipy as sp
from scipy.linalg import svd,null_space
import os
from sklearn.metrics.pairwise import pairwise_kernels
from sklearn.cluster import KMeans,AgglomerativeClustering,SpectralClustering
from sklearn.mixture import GaussianMixture
from scipy.sparse import csr_matrix as sp
import math
from scipy.sparse.linalg import svds
from scipy.spatial.distance import cdist
from mpl_toolkits.mplot3d import Axes3D  # Import 3D plotting tools
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture



In [2]:

# Hàm	Độ phức tạp tính toán	Bộ nhớ cần
# preprocess_data_OC	O(n⋅d²)	O(n⋅d²)
# clusterr	O(n⋅d⋅k⋅iters)	O(n⋅d)
# nullspace	O(d³)	O(d²)
# gram_schmidt	O(d³)	O(d²)
# minimum_distance	O(n⋅m⋅d)	O(n⋅m)
# distance_vector	O(n⋅m⋅d)	O(n⋅m)
# calculate_NPD	O(d³)	O(d²)
# learn	O(n²⋅d)	O(n²)



alpha = 0.9 

In [3]:

def preprocess_data_noise(train_data, test_data, noise_percentage=0):
  
    print("..............................Data Overview................................")
    print("Train Data Shape:", train_data.shape)
    print("Test Data Shape:", test_data.shape)
    
    # Convert to numpy arrays for easier manipulation
    X_train_total = train_data.iloc[:, :-1].to_numpy()
    y_train_total = train_data.iloc[:, -1].to_numpy()

    # Separate the samples with label 0
    X_train = X_train_total[y_train_total == 0]
    y_train = y_train_total[y_train_total == 0]

    print("Train Data Labels [0]:", np.unique(y_train))

    # Calculate how many samples to add noise to based on the provided percentage
    n_samples = X_train.shape[0]
    noise_samples_count = int(n_samples * (noise_percentage / 100))

    # Get the samples with label 1 (for generating noise)
    X_train_noise = X_train_total[y_train_total == 1]
    
    # Randomly select noise_samples_count from X_train_noise
    noisy_indices = np.random.choice(X_train_noise.shape[0], size=noise_samples_count, replace=False)
    X_train_noise = X_train_noise[noisy_indices]
    
    # Add the noisy samples to the training set
    X_train = np.vstack((X_train, X_train_noise))
    y_train = np.concatenate((y_train, np.ones(X_train_noise.shape[0])))
    print(y_train) 
    
    # Prepare test data
    X_test = test_data.iloc[:, :-1].to_numpy()
    y_test = test_data.iloc[:, -1].to_numpy()

    # Print the new size of training data
    n_samples = X_train.shape[0]
    n_features = X_train.shape[1]
    print("Number of samples after adding noise:", n_samples)
    print("Number of features:", n_features)

    return X_train, y_train, X_test, y_test



def cluster_kmeans(data, initial_k):
    print("Starting K-Means clustering...")

    # Thực hiện K-Means clustering với số cụm initial_k
    kmeans = KMeans(n_clusters=initial_k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(data)

    # Gán nhãn cụm vào biến labels
    labels = cluster_labels

    # Sắp xếp dữ liệu theo nhãn cụm
    sorted_indices = np.argsort(labels)
    sorted_data = data[sorted_indices]
    sorted_labels = labels[sorted_indices]

    print("Final number of clusters:", len(np.unique(sorted_labels)))
    return sorted_data, sorted_labels


In [4]:
def nullspace(A):
    _, s, vh = np.linalg.svd(A)
    null_mask = np.isclose(s, 0)
    null_space = vh[null_mask].T
    return null_space


def minimum_distance( A, B):
        """
        Compute the minimum Euclidean distance from each point in A to all points in B.
        
        Parameters:
        - A (ndarray): Set of points (N_A, d).
        - B (ndarray): Set of points (N_B, d).
        
        Returns:
        - min_distances (ndarray): Minimum distances from each point in A to the nearest point in B.
        """
        A = np.asarray(A)
        B = np.asarray(B)
        
        # Initialize an array for storing minimum distances
        min_distances = np.empty(A.shape[0], dtype=np.float64)
        
        # Iterate over each point in A and calculate minimum distance to points in B
        for i, a in enumerate(A):
            distances = cdist([a], B, metric='euclidean')  # Compute all pairwise distances
            min_distances[i] = np.min(distances)  # Store minimum distance
        
        return min_distances   

def distance_vector(point_X, point_Y):
    """
    Calculate pairwise Euclidean distance between two sets of points.
    
    Args:
        point_X (ndarray): Array of shape (N_train, d) where N_train is the number of training samples and d is the number of features.
        point_Y (ndarray): Array of shape (N_test, d) where N_test is the number of test samples and d is the number of features.
        
    Returns:
        ndarray: Distance matrix of shape (N_test, N_train) containing Euclidean distances between each pair of points.
    """
    print( 'Complexity of calculate: ', point_X )
    # Compute squared norms for each point
    norm_X = np.sum(point_X**2, axis=1)  # (N_train,)
    norm_Y = np.sum(point_Y**2, axis=1)  # (N_test,)
    
    # Compute the dot product between the two sets of points
    dot_product = np.dot(point_Y, point_X.T)  # (N_test, N_train)
    
    # Apply Euclidean distance formula
    distance = np.sqrt(abs(norm_Y[:, np.newaxis] + norm_X[np.newaxis, :] - 2 * dot_product))
    return distance



def calculate_NPD(X,y):
    print("Begin calculating NPD --------------")
    X = X.T
    print('shape of X', X.shape)
    c = len(np.unique(y))  # Số lớp
    d, N = X.shape  # Số đặc trưng và số mẫu
    # Tính trung bình toàn cục và tạo ma trận P_t với zero-mean
    mean_total = np.mean(X, axis=1, keepdims=True)
    P_t = X - mean_total  # P_t là ma trận zero-mean có kích thước d x N
    
    # Tính P_w cho từng lớp
    P_w = np.zeros_like(X)
    for i in range(c):
        class_mean = np.mean(X[:, y == i], axis=1, keepdims=True)
        P_w[:, y == i] = X[:, y == i] - class_mean  # Tạo ma trận P_w có kích thước d x N
        
    # Tính ma trận phương sai S_w và S_t
    S_w = np.dot(P_w, P_w.T) / N  # S_w là d x d
    S_t = np.dot(P_t, P_t.T) / N  # S_t là d x d

    U, S, Vt = np.linalg.svd(P_t, full_matrices=False)
    Q = U
    B = nullspace(Q.T @ S_w @ Q)
    W = Q @ B  # W có kích thước d x (c - 1)

    # In kết quả
    print("N =", N,  "  d =", d, "   c =", c )
    print("P_w : d x N =", P_w.shape)  # d x N
    print("P_t : d x N =", P_t.shape)  # d x N
    print("S_w : d x d =", S_w.shape)  # d x d
    print("S_t : d x d =", S_t.shape)  # d x d
    print("Q   : d x N =", Q.shape)     # d x r
    print("B   : N x L =", B.shape)     # r x L
    print("W   : d x L =", W.shape)     # d x L
    return W    

    

def BruteForce_Threshold(y_true, y_prob, minth=0.0, maxth=1.0, num_thresholds=1000):
    """
    Finds the best classification threshold for a binary model using brute force search.

    Args:
        y_true (ndarray): True labels (0 or 1), shape (n_samples,).
        y_prob (ndarray): Predicted probabilities for class 1, shape (n_samples,).
        minth (float, optional): Minimum threshold value. Default is 0.0.
        maxth (float, optional): Maximum threshold value. Default is 1.0.
        num_thresholds (int, optional): Number of threshold values to search. Default is 1000.

    Returns:
        dict: Dictionary containing the best threshold for each evaluation metric.
    """
    thresholds = np.linspace(minth, maxth, num_thresholds)  # Generate candidate thresholds

    # Initialize best metrics
    best_results = {
        "accuracy": (0, 0),  # (best_threshold, best_score)
        "f1": (0, 0),
        "mcc": (0, 0),
        "auc_roc": (0, 0),
        "auc_pr": (0, 0)
    }

    return best_results 
    for threshold in thresholds:
        y_pred = (y_prob[:,1] >= threshold).astype(int)

        # Compute evaluation metrics
        acc = accuracy_score(y_true, y_pred)
        f1 = f1_score(y_true, y_pred)
        mcc = matthews_corrcoef(y_true, y_pred)
        auc_roc = roc_auc_score(y_true, y_prob[:, 1])
        auc_pr = average_precision_score(y_true, y_prob[:, 1])

        # Update best threshold for each metric
        if acc > best_results["accuracy"][1]:
            best_results["accuracy"] = (threshold, acc)
        if f1 > best_results["f1"][1]:
            best_results["f1"] = (threshold, f1)
        if mcc > best_results["mcc"][1]:
            best_results["mcc"] = (threshold, mcc)
        if auc_roc > best_results["auc_roc"][1]:
            best_results["auc_roc"] = (threshold, auc_roc)
        if auc_pr > best_results["auc_pr"][1]:
            best_results["auc_pr"] = (threshold, auc_pr)

    return best_results


def learn(npd, X_train, y_train, X_test,  y_test ):
    t0 = time.time()
    '''
    X_train: n1, d      (Training set with n1 samples, d features)
    npd: n * n * d      (Some kind of transformation matrix, depending on context)
    X_test: n_test, d   (Test set)
    y_train: Labels for training set (not used directly here, but could be useful)
    t0: Starting time for measuring execution time
    '''
    t1 = time.time()
    
    # Compute the null point projections
    null_point_X = (sp(X_train).dot(sp(npd))).toarray()
    null_point_X_test = (sp(X_test).dot(sp(npd))).toarray()  

    # Calculate pairwise distances for training
    train_score_tmp = distance_vector(null_point_X, null_point_X)
    for i in range(len(train_score_tmp)):
        train_score_tmp[i, i] = 1e9  # Avoid self-distance being considered
    train_score = np.amin(train_score_tmp, axis=1)

    # Calculate the minimum distance for test samples
    y_score = minimum_distance(null_point_X_test, null_point_X)
    
    # Initialize probability array for both classes (for each test sample)
    y_proba = np.zeros((len(y_score), 2))

    # Track the best AUC and corresponding probabilities
    max_auc = -np.inf
    best_y_proba = None

    # Iterate through 100 to 1 to calculate the class probabilities
    for i in range(-100, 100 , 1):  # 100 iterations
        nu = np.max(train_score) + (np.max(train_score) * i) / 100  # Scaling factor for nu
        
        # Calculate probabilities for class 1 (y_proba[:, 1]) and class 0 (y_proba[:, 0])
        y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
        y_proba[:, 0] = 1 - y_proba[:, 1]  # Class 0 probability

        # Replace NaN values with 1.0 in the probabilities (in case of issues)
        y_proba = np.nan_to_num(y_proba, nan=1.0)
        
        # Calculate AUC for this iteration
        auc = roc_auc_score(y_test, y_proba[:, 1])

        # Track the best AUC and corresponding probabilities
        if auc > max_auc:
            max_auc = auc
            best_y_proba = y_proba

    print( max_auc)

    # Classify based on a threshold for class 1 (i.e., 0.2)
    y_predict = (best_y_proba[:, 1] > 0.2).astype(int)

    t2 = time.time()
    print("...............................Timing Model................................")
    print("Time train:", t1 - t0)
    print("Time test:", t2 - t1)
    
    
    return y_proba, y_predict, t1, t2
    

def Model_evaluating(y_true, y_predict, y_scores):
    """
    Evaluate the model using various metrics such as AUC, AUCPR, Accuracy, MCC, F1-score, Precision, and Recall.
    
    Args:
        y_true (ndarray): True labels.
        y_predict (ndarray): Predicted labels.
        y_scores (ndarray): Predicted probabilities for each class.
        
    Returns:
        list: List of evaluation metrics.
    """
    print("..............................Report Parameter...............................")
    
    # Calculate MCC (Matthews Correlation Coefficient)
    mcc = matthews_corrcoef(y_true, y_predict)
    
    # Calculate F1 score
    f1 = f1_score(y_true, y_predict)
    
    # Calculate PPV (Positive Predictive Value) or Precision
    ppv = precision_score(y_true, y_predict)
    
    # Calculate TPR (True Positive Rate) or Recall/Sensitivity
    tpr = recall_score(y_true, y_predict)
    
    # Calculate Accuracy
    accuracy = accuracy_score(y_true, y_predict)
    
    # Calculate AUC (Area Under ROC Curve)
    AUC = roc_auc_score(y_true, y_scores[:, 1])
    
    # Calculate AUCPR (Area Under Precision-Recall Curve)
    AUCPR = average_precision_score(y_true, y_scores[:, 1])
    
    # Print out the evaluation metrics
    print("AUCROC:", AUC * 100)
    print("AUCPR:", AUCPR * 100)
    print("Accuracy:", accuracy * 100)
    print("MCC:", mcc)
    print("F1 score:", f1)
    print("PPV (Precision):", ppv)
    print("TPR (Recall):", tpr)

    return [AUC * 100 if AUC else None, AUCPR * 100 if AUCPR else None,
            accuracy * 100, mcc, f1, ppv, tpr]



In [5]:
# X_train, y_train, X_test, y_test = preprocess_data_OC(df2, df1)

# X_total = np.vstack((X_train, X_test))
# unique_rows = np.unique(X_total, axis=0)

# print("Số dòng trong X_total:", X_total.shape[0])   # Output: 5
# print("Số dòng khác nhau:", unique_rows.shape[0])  

In [6]:

import pandas as pd

# Load the CSV files from the GMM-nfst folder

columns = ["scaler","nCluster", 'noise_percentage', "AUCROC", "AUCPR", "Accuracy", "MCC", "F1 Score",
           "Precision", "Recall", "Time Train", "Time Test"]
# Now you can use df1 and df2 as DataFrames

#CIC_IoT2023_1000.csv
#N_BaIoT_1000.csv
#BoT_IoT_1000.csv

import cProfile
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np


# def plot_data_2D(X, labels, title="Interactive 3D PCA Plot"):
#     """ Vẽ dữ liệu với PCA và tạo đồ thị 3D có thể tương tác bằng Plotly """

#     # Ensure that n_components ≤ min(n_samples, n_features)
#     n_components = min(3, X.shape[0], X.shape[1])
#     if n_components < 3:
#         print(f"⚠️ Warning: Cannot plot 3D, because n_components={n_components}. Skipping...")
#         return
    
#     # Perform PCA
#     pca = PCA(n_components=3)
#     X_3D = pca.fit_transform(X)

#     # Convert labels to a NumPy array
#     labels = np.array(labels)

#     # Create a DataFrame for better visualization
#     import pandas as pd
#     df = pd.DataFrame(X_3D, columns=['PCA 1', 'PCA 2', 'PCA 3'])
#     df['Class'] = labels

#     # Create an interactive 3D scatter plot
#     fig = px.scatter_3d(df, x='PCA 1', y='PCA 2', z='PCA 3', 
#                          color=df['Class'].astype(str),  # Color by class
#                          title=title, labels={'color': 'Class'},
#                          opacity=0.8)

#     fig.update_traces(marker=dict(size=5))  # Adjust marker size
#     fig.show()

from sklearn.impute import SimpleImputer

def plot_data_2D(X, labels, title="Dữ liệu gốc trước khi biến đổi"):
    """ Vẽ dữ liệu với PCA để giảm xuống 2D """
    return 0 
    pca = PCA(n_components=3)
    X_2D = pca.fit_transform(X)  # Chuyển về dạng (100, 2)

    plt.figure(figsize=(8, 6))
    labels = np.array(labels)  
    for i in np.unique(labels):
        plt.scatter(X_2D[labels == i, 0], X_2D[labels == i, 1], label=f"Class {i}", alpha=0.7)

    plt.xlabel("PCA 1")
    plt.ylabel("PCA 2")
    plt.title(title)
    plt.legend()
    plt.grid()
    plt.show()


def function(df1,df2, scaler, noise):

    X_train0, y_train0, X_test, y_test = preprocess_data_noise( df1,df2, noise)

    imputer = SimpleImputer(strategy="mean") 
    X_train0[np.isinf(X_train0)] = np.nan  # Đổi vô hạn thành NaN
    X_train0 = imputer.fit_transform(X_train0)
    for ncluster in range(1, 30,2):
        t0 = time.time()
        X_train , y_train = cluster_kmeans( X_train0 , ncluster )
        plot_data_2D(X_train, y_train, "Du lieu sau clusterr") 
        npd = calculate_NPD(X_train, y_train)
        
        y_proba, y_predict, t1, t2 = learn( npd , X_train, y_train, X_test, y_test)  #,y_predict
        
        # print("...............................Timing Model................................")
        # print("Time train:", t1-t0)
        # print("Time test:" , t2-t1)
        # print("...........................................................................")
        # print(y_predict)
        v = Model_evaluating(y_test, y_predict, y_proba)
        # best_thresholds = BruteForce_Threshold( y_test, y_proba, 0, 1)  
        result = [scaler] + [ncluster] + [noise] + v + [t1-t0, t2-t1]
        # for metric, (threshold, score) in best_thresholds.items():
        #     result = result + [threshold, score ]  

        result_df = pd.DataFrame([result], columns=columns)
        result_df.to_csv(output_file, mode='a', header=not os.path.exists(output_file), index=False)
        # result_df.to_csv(output_file, mode='a', header=(mark==0), index=False)
        
    return 0


In [7]:

import cProfile
import pstats    

# dataset_prefixes =  ['N_BaIoT_dataloader.csv']
dataset_prefixes =  ['data_BoTIoT.csv']
#  'data_N_BaIoT.csv',  
# scaler_names = ['MinMaxScaler']
scaler_names = ['Normalizer','MinMaxScaler', 'StandardScaler', 'QuantileTransformer']
#  
# scaler_names = ['QuantileTransformer', 'StandardScaler','QuantileTransformer']

    # Iterate through dataset prefixes and process each dataset pair



for prefix in dataset_prefixes:
    
    print("-"*50)
    print("--------", prefix , "-"*30)
    print("-"*50)

    base_output_file = f"Results/OURMODEL/SCALERS/{prefix}_100k_oldlearn" 
    output_file = base_output_file + "0.csv"

    # Increment the filename if it already exists
    counter = 0
    while os.path.exists(output_file):
        counter += 1
        output_file = f"{base_output_file}{counter}.csv"

        
    for scaler in scaler_names: 
        print(f"Processing dataset {prefix} with {scaler} scaler ...")
        
        # Construct file paths for train and test datasets with 'Train_' and 'Test_' prefixes
        train_file = f'Datascaled/Train_{scaler}_{prefix}'
        test_file = f'Datascaled/Test_{scaler}_{prefix}'
        
        # Load the CSV files
        df_train = pd.read_csv(train_file)
        df_test = pd.read_csv(test_file)

        for noise in range (0, 1): 
            
            # log_file = f'Results/OURMODEL/SCALERS/{prefix}_modellog.txt'
            # with open(log_file, "w") as f:
            #     profiler = cProfile.Profile()
            #     profiler.enable()
                
            function(df_train, df_test, scaler, noise)  # Chạy hàm cần profile
            
                # profiler.disable()
                # stats = pstats.Stats(profiler, stream=f)
                # stats.sort_stats("cumulative").print_stats()

--------------------------------------------------
-------- data_BoTIoT.csv ------------------------------
--------------------------------------------------
Processing dataset data_BoTIoT.csv with Normalizer scaler ...
..............................Data Overview................................
Train Data Shape: (66929, 27)
Test Data Shape: (28685, 27)
Train Data Labels [0]: [0]
[0. 0. 0. ... 0. 0. 0.]
Number of samples after adding noise: 6359
Number of features: 26
Starting K-Means clustering...
Final number of clusters: 1
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 1
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 22)
W   : d x L = (26, 22)
Complexity of calculate:  [[-1.20896249e-02 -1.16062323e-05 -1.69208242e-03 ...  1.27396508e-09
  -2.81771301e-10  3.16123974e-10]
 [-1.19946072e-02 -1.37626249e-05 -1.68939865e-03 ...  1.27289785e-09
  -2.81591553e-10

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8955904708742735
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 2.9945802688598633
..............................Report Parameter...............................
AUCROC: 89.55691828149843
AUCPR: 98.45093953136201
Accuracy: 46.86072860379989
MCC: 0.23338495911901155
F1 score: 0.5864510702949076
PPV (Precision): 0.9927436392027188
TPR (Recall): 0.41614045895579854
Starting K-Means clustering...
Final number of clusters: 3
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 3
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 22)
W   : d x L = (26, 22)
Complexity of calculate:  [[-1.87222228e-02 -1.58072090e-06 -2.49529241e-03 ...  1.04358089e-11
  -4.18110908e-15  3.77430680e-08]
 [-1.86348307e-02 -3.18657263e-06 -2.49535405e-03 ...  1.04087926e-11
  -4.17530092e-15  3.77453374e-08]
 [-1.86432623e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8929608704466048
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.0221364498138428
..............................Report Parameter...............................
AUCROC: 89.28893425673932
AUCPR: 98.38440573562933
Accuracy: 54.96601010981349
MCC: 0.26621074438631176
F1 score: 0.6714816133462185
PPV (Precision): 0.9889138576779026
TPR (Recall): 0.5083166486985985
Starting K-Means clustering...
Final number of clusters: 5
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 5
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.99052676e-01 -2.21289159e-02 -1.35620408e-05 ... -4.78427802e-12
  -1.76086939e-13 -1.86818447e-15]
 [-9.98935576e-01 -2.22342259e-02 -1.14014687e-05 ... -4.80476423e-12
  -1.76516559e-13 -1.86858471e-15]
 [-9.98951707e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8861531122943993
...............................Timing Model................................
Time train: 7.152557373046875e-07
Time test: 3.1123557090759277
..............................Report Parameter...............................
AUCROC: 88.61505506312646
AUCPR: 98.14462492032668
Accuracy: 13.975945616175704
MCC: 0.0611312310885258
F1 score: 0.09624963375329622
PPV (Precision): 0.9864864864864865
TPR (Recall): 0.05059294624980749
Starting K-Means clustering...
Final number of clusters: 7
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 7
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.98114075e-01 -2.99520384e-02  1.53536399e-04 ...  2.64677497e-11
  -5.46941762e-14 -1.29194195e-15]
 [-9.98103771e-01 -2.98597091e-02  1.51823878e-04 ...  2.68692829e-11
  -5.49313511e-14 -1.28243075e-15]
 [-9.98119813

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8700426567293627
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.090409755706787
..............................Report Parameter...............................
AUCROC: 87.00414787900822
AUCPR: 97.89506535213958
Accuracy: 15.781767474289698
MCC: 0.07354965319550437
F1 score: 0.13206869296543797
PPV (Precision): 0.9871106337271751
TPR (Recall): 0.07076851994455567
Starting K-Means clustering...
Final number of clusters: 9
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 9
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.97425889e-01 -3.06321203e-02  1.47611002e-04 ... -4.24474794e-11
  -2.26700650e-13 -8.38860637e-16]
 [-9.97415970e-01 -3.05397763e-02  1.45898085e-04 ... -4.28488906e-11
  -2.30241541e-13 -8.21133585e-16]
 [-9.97428884

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8754915341929659
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 3.1096105575561523
..............................Report Parameter...............................
AUCROC: 87.3939166333485
AUCPR: 97.82418083064438
Accuracy: 73.80861077218059
MCC: 0.3489695527683233
F1 score: 0.8343512291919303
PPV (Precision): 0.9761646803900325
TPR (Recall): 0.7285153241952872
Starting K-Means clustering...
Final number of clusters: 11
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 11
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.98020271e-01 -4.92396396e-02 -3.22980701e-04 ...  8.51198419e-11
  -2.84882116e-14  7.38155909e-15]
 [-9.97998237e-01 -4.91472153e-02 -3.24521377e-04 ...  8.51851701e-11
  -2.85385140e-14  7.38150299e-15]
 [-9.98009467e-0

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8849613570632561
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.0379302501678467
..............................Report Parameter...............................
AUCROC: 88.49267142947728
AUCPR: 98.13273576465808
Accuracy: 28.81296845040962
MCC: 0.14696479761411838
F1 score: 0.354001898133502
PPV (Precision): 0.9923731819794254
TPR (Recall): 0.21542430309564145
Starting K-Means clustering...
Final number of clusters: 13
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 13
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.97815273e-01 -5.37569318e-02 -1.68646916e-04 ...  1.09231551e-10
  -1.26392462e-14  6.78436577e-15]
 [-9.97778168e-01 -5.37795680e-02 -1.68148166e-04 ...  1.09178869e-10
  -1.26800752e-14  6.78507366e-15]
 [-9.97792336

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.874697361853126
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.1212308406829834
..............................Report Parameter...............................
AUCROC: 87.46878957627621
AUCPR: 98.01350816075383
Accuracy: 25.319853582011504
MCC: 0.12855751689038944
F1 score: 0.30002614037380737
PPV (Precision): 0.9911485319516408
TPR (Recall): 0.1767672878484522
Starting K-Means clustering...
Final number of clusters: 15
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 15
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.89255158e-01 -1.43082422e-01 -5.55900577e-04 ...  1.77799293e-11
   3.18930744e-14  1.05994008e-14]
 [-9.89255270e-01 -1.42995995e-01 -5.57388066e-04 ...  1.77290127e-11
   3.19197912e-14  1.06030169e-14]
 [-9.8925241

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8720743749158768
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 3.1269164085388184
..............................Report Parameter...............................
AUCROC: 87.2067662081181
AUCPR: 97.97787092760353
Accuracy: 14.88234268781593
MCC: 0.06805557912774683
F1 score: 0.11433546140452698
PPV (Precision): 0.9874686716791979
TPR (Recall): 0.06068073309718158
Starting K-Means clustering...
Final number of clusters: 17
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 17
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.86640980e-01 -1.59872372e-01 -6.80899863e-04 ...  1.35683232e-12
   1.40026805e-14 -1.16653305e-11]
 [-9.86642224e-01 -1.59786241e-01 -6.82391824e-04 ...  1.35091546e-12
   1.38985934e-14 -1.16139999e-11]
 [-9.86639384

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8687716886296046
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.1100869178771973
..............................Report Parameter...............................
AUCROC: 86.8765628628727
AUCPR: 97.88097712707142
Accuracy: 15.356458079135438
MCC: 0.07015337980992237
F1 score: 0.12384526558891455
PPV (Precision): 0.9862068965517241
TPR (Recall): 0.0660711535499769
Starting K-Means clustering...
Final number of clusters: 19
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 19
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.67488550e-01 -2.51840287e-01 -1.07160800e-03 ... -3.03242015e-10
   1.38369758e-14  1.26611804e-14]
 [-9.67466217e-01 -2.51824077e-01 -1.07192793e-03 ... -3.03553884e-10
   1.38403862e-14  1.26606994e-14]
 [-9.6746962

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8822728667675739
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.101972818374634
..............................Report Parameter...............................
AUCROC: 88.22533881933245
AUCPR: 98.03651169390166
Accuracy: 27.889140665853233
MCC: 0.1398937910563574
F1 score: 0.34042281814993147
PPV (Precision): 0.9905362776025236
TPR (Recall): 0.20552903126443864
Starting K-Means clustering...
Final number of clusters: 23
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 23
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-9.12222013e-01 -4.08639261e-01  7.10506151e-04 ... -7.24195779e-13
   1.34655448e-14  1.38022903e-10]
 [-9.12191789e-01 -4.08719371e-01  7.12205196e-04 ... -7.22904133e-13
   1.34652913e-14  1.37924093e-10]
 [-9.1222079

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8678215883514919
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.049640655517578
..............................Report Parameter...............................
AUCROC: 86.78123777178394
AUCPR: 97.82952684575905
Accuracy: 19.466620184765556
MCC: 0.09827929549047389
F1 score: 0.20057445409558086
PPV (Precision): 0.9907692307692307
TPR (Recall): 0.11158170337286308
Starting K-Means clustering...
Final number of clusters: 25
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 25
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-8.81492346e-01 -4.70958630e-01 -1.34906205e-03 ...  3.76599715e-14
  -1.42221003e-14 -1.05635905e-11]
 [-8.81522861e-01 -4.70878142e-01 -1.35052834e-03 ...  3.76636590e-14
  -1.42220017e-14 -1.05516703e-11]
 [-8.815213

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8742117102605438
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.0670790672302246
..............................Report Parameter...............................
AUCROC: 87.4197688525492
AUCPR: 97.92010552229712
Accuracy: 20.82272964964267
MCC: 0.10608763152243124
F1 score: 0.22458176852167977
PPV (Precision): 0.9912597950572634
TPR (Recall): 0.12663637763745572
Starting K-Means clustering...
Final number of clusters: 27
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 27
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 23)
W   : d x L = (26, 23)
Complexity of calculate:  [[-7.89321932e-01 -6.13250477e-01  6.17423158e-04 ... -3.08107287e-13
   8.28104410e-10 -1.54930453e-14]
 [-7.89317548e-01 -6.13237996e-01  6.17400485e-04 ... -3.08029274e-13
   8.27409026e-10 -1.54931448e-14]
 [-7.8929758

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8652125379970569
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 3.0900790691375732
..............................Report Parameter...............................
AUCROC: 86.51931374790249
AUCPR: 97.77186657374233
Accuracy: 23.68833885305909
MCC: 0.12081205206358801
F1 score: 0.2733851158467768
PPV (Precision): 0.9913336543090997
TPR (Recall): 0.15855536731865086
Processing dataset data_BoTIoT.csv with MinMaxScaler scaler ...
..............................Data Overview................................
Train Data Shape: (66929, 27)
Test Data Shape: (28685, 27)
Train Data Labels [0]: [0]
[0. 0. 0. ... 0. 0. 0.]
Number of samples after adding noise: 6359
Number of features: 26
Starting K-Means clustering...
Final number of clusters: 1
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 1
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q  

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7987076331430446
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0082669258117676
..............................Report Parameter...............................
AUCROC: 79.87050927679692
AUCPR: 97.52804589320027
Accuracy: 11.765731218406833
MCC: 0.046120342644554814
F1 score: 0.05006755742381024
PPV (Precision): 0.9925595238095238
TPR (Recall): 0.025681503157246266
Starting K-Means clustering...
Final number of clusters: 7
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 7
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-2.32059356e-06 -1.21293392e-07 -4.54872882e-05]
 [-2.32059356e-06 -1.21293392e-07 -4.54874639e-05]
 [-2.32059356e-06 -1.21293392e-07 -4.54875155e-05]
 ...
 [-2.32059356e-06 -1.21293392e-07 -4.54875178e-05]
 [-2.32059356

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7832198746002742
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.045748233795166
..............................Report Parameter...............................
AUCROC: 78.3217390993357
AUCPR: 97.34311145050053
Accuracy: 11.765731218406833
MCC: 0.046120342644554814
F1 score: 0.05006755742381024
PPV (Precision): 0.9925595238095238
TPR (Recall): 0.025681503157246266
Starting K-Means clustering...
Final number of clusters: 9
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 9
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54876071e-05  2.23506789e-06 -6.36710842e-07]
 [-4.54875341e-05  2.23506789e-06 -6.36710842e-07]
 [-4.54875338e-05  2.23506789e-06 -6.36710842e-07]
 ...
 [-4.54874579e-05  2.23506789e-06 -6.36710842e-07]
 [-4.54875454e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7448767163072041
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.032883882522583
..............................Report Parameter...............................
AUCROC: 74.4875609328121
AUCPR: 96.71955153687675
Accuracy: 11.727383649991284
MCC: 0.045667350255685
F1 score: 0.04926219351931815
PPV (Precision): 0.9924357034795764
TPR (Recall): 0.02525797012166949
Starting K-Means clustering...
Final number of clusters: 17
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 17
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54879524e-05  2.29371470e-06  3.72808974e-07]
 [-4.54879294e-05  2.29371470e-06  3.72808974e-07]
 [-4.54879268e-05  2.29371470e-06  3.72808974e-07]
 ...
 [-4.54874997e-05  2.29371470e-06  3.72808974e-07]
 [-4.54874712e-05

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7658002743491544
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0419423580169678
..............................Report Parameter...............................
AUCROC: 76.5790105752834
AUCPR: 97.11442627142857
Accuracy: 21.09116262855151
MCC: 0.11461932182875655
F1 score: 0.22813299232736572
PPV (Precision): 0.9976140769460184
TPR (Recall): 0.12879254581857386
Starting K-Means clustering...
Final number of clusters: 19
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 19
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54875533e-05 -2.29135439e-06 -3.86994949e-07]
 [-4.54875600e-05 -2.29135439e-06 -3.86994949e-07]
 [-4.54875090e-05 -2.29135439e-06 -3.86994949e-07]
 ...
 [-4.54874417e-05 -2.29135439e-06 -3.86994949e-07]
 [-4.54875091e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.6095480195888747
...............................Timing Model................................
Time train: 7.152557373046875e-07
Time test: 2.025184154510498
..............................Report Parameter...............................
AUCROC: 60.95445638272502
AUCPR: 94.37260186572863
Accuracy: 12.480390447969322
MCC: 0.05208136241694548
F1 score: 0.06516477378514243
PPV (Precision): 0.9909399773499433
TPR (Recall): 0.03369012782997074
Starting K-Means clustering...
Final number of clusters: 21
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 21
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 2.23843949e-06  6.24112355e-07 -4.54878568e-05]
 [ 2.23843949e-06  6.24112355e-07 -4.54878784e-05]
 [ 2.23843949e-06  6.24112355e-07 -4.54878507e-05]
 ...
 [ 2.23843949e-06  6.24112355e-07 -4.54877547e-05]
 [ 2.23843949e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7376135994707844
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0136733055114746
..............................Report Parameter...............................
AUCROC: 73.75995209675746
AUCPR: 96.49939060348454
Accuracy: 22.729649642670385
MCC: 0.12393372179057252
F1 score: 0.2560832354421883
PPV (Precision): 0.9979074025634319
TPR (Recall): 0.1468889573386724
Starting K-Means clustering...
Final number of clusters: 23
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 23
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54877948e-05  2.31960316e-06 -1.39386366e-07]
 [-4.54879575e-05  2.31960316e-06 -1.39386366e-07]
 [-4.54878345e-05  2.31960316e-06 -1.39386366e-07]
 ...
 [-4.54872545e-05  2.31960316e-06 -1.39386366e-07]
 [-4.54873565e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7066124231777804
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0045015811920166
..............................Report Parameter...............................
AUCROC: 70.66072288913139
AUCPR: 96.1334575626596
Accuracy: 13.82255534251351
MCC: 0.06383352777079429
F1 score: 0.09264425194538248
PPV (Precision): 0.9921383647798742
TPR (Recall): 0.04859079008162637
Starting K-Means clustering...
Final number of clusters: 25
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 25
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 2.32244833e-06 -4.54879001e-05 -7.85946930e-08]
 [ 2.32244833e-06 -4.54877453e-05 -7.85946932e-08]
 [ 2.32244833e-06 -4.54878368e-05 -7.85946932e-08]
 ...
 [ 2.32244833e-06 -4.54872348e-05 -7.85946930e-08]
 [ 2.32244833e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.737217279670999
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 2.013009786605835
..............................Report Parameter...............................
AUCROC: 73.72129440029238
AUCPR: 96.5971693239037
Accuracy: 13.50880251002266
MCC: 0.06315785647684569
F1 score: 0.08605319384071318
PPV (Precision): 0.9948892674616695
TPR (Recall): 0.044971507777606654
Starting K-Means clustering...
Final number of clusters: 27
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 27
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54881364e-05  2.29031130e-06  3.90446687e-07]
 [-4.54878642e-05  2.29031130e-06  3.90446687e-07]
 [-4.54878104e-05  2.29031130e-06  3.90446687e-07]
 ...
 [-4.54874041e-05  2.29031131e-06  3.90446687e-07]
 [-4.54872003e-05

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7253306660057339
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0282938480377197
..............................Report Parameter...............................
AUCROC: 72.53170345517691
AUCPR: 96.49073079891275
Accuracy: 22.959735053163673
MCC: 0.12521324248240664
F1 score: 0.2599377113961354
PPV (Precision): 0.997942915916688
TPR (Recall): 0.14943015555213307
Starting K-Means clustering...
Final number of clusters: 29
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 29
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-4.54870683e-05 -7.00341571e-07 -2.21580787e-06]
 [-4.54871045e-05 -7.00341571e-07 -2.21580787e-06]
 [-4.54870664e-05 -7.00341571e-07 -2.21580787e-06]
 ...
 [-4.54872436e-05 -7.00341571e-07 -2.21580787e-06]
 [-4.54873537e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.5314730474152067
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 2.0319812297821045
..............................Report Parameter...............................
AUCROC: 53.147057800032904
AUCPR: 92.21221457694975
Accuracy: 11.640230085410494
MCC: 0.044622452964577834
F1 score: 0.047429344558027664
PPV (Precision): 0.9921383647798742
TPR (Recall): 0.024295395040813184
Processing dataset data_BoTIoT.csv with StandardScaler scaler ...
..............................Data Overview................................
Train Data Shape: (66929, 27)
Test Data Shape: (28685, 27)
Train Data Labels [0]: [0]
[0. 0. 0. ... 0. 0. 0.]
Number of samples after adding noise: 6359
Number of features: 26
Starting K-Means clustering...
Final number of clusters: 1
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 1
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8036901743798603
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0301284790039062
..............................Report Parameter...............................
AUCROC: 80.36873501639947
AUCPR: 97.39653068572672
Accuracy: 12.333972459473593
MCC: 0.05052058053482814
F1 score: 0.06213403945847165
PPV (Precision): 0.990487514863258
TPR (Recall): 0.032073001694132144
Starting K-Means clustering...
Final number of clusters: 3
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 3
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-7.08069985e-14 -1.10465337e-13 -2.73139281e-09]
 [ 1.64011446e-12 -1.66180997e-13 -3.64860338e-09]
 [-7.89490148e-13 -7.38481161e-14 -2.76443650e-09]
 ...
 [-1.87865234e-13 -9.51677332e-14 -2.41382350e-09]
 [-1.90588480e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8016884723569441
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.044635057449341
..............................Report Parameter...............................
AUCROC: 80.16857191012761
AUCPR: 97.41034112547162
Accuracy: 12.316541746557434
MCC: 0.05033196989336408
F1 score: 0.06177260519247985
PPV (Precision): 0.9904306220095693
TPR (Recall): 0.03188048667796088
Starting K-Means clustering...
Final number of clusters: 5
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 5
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[1.53750311e-13 3.53350574e-14 2.39795050e-09]
 [1.49468016e-13 2.46227421e-14 2.42985976e-09]
 [1.60643184e-13 4.22010707e-14 2.43843278e-09]
 ...
 [2.23760192e-13 3.76737926e-13 3.46422050e-09]
 [1.57018995e-13 2.38038788e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7824364882104741
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0026798248291016
..............................Report Parameter...............................
AUCROC: 78.24336356105293
AUCPR: 97.26384957167147
Accuracy: 12.316541746557434
MCC: 0.05033196989336408
F1 score: 0.06177260519247985
PPV (Precision): 0.9904306220095693
TPR (Recall): 0.03188048667796088
Starting K-Means clustering...
Final number of clusters: 7
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 7
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 1.13901328e-13  2.32870690e-13 -6.98785461e-09]
 [ 1.10456397e-13  2.28610500e-13 -7.12688757e-09]
 [ 1.13236589e-13  2.32304562e-13 -7.00639744e-09]
 ...
 [ 1.27208969e-13  4.24633790e-13 -1.63117312e-08]
 [ 1.77127302e-

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.8545933444216685
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.041405439376831
..............................Report Parameter...............................
AUCROC: 85.45860213292728
AUCPR: 97.88082988658284
Accuracy: 11.873801638487013
MCC: 0.047375974120387854
F1 score: 0.05233364573570758
PPV (Precision): 0.9928876244665719
TPR (Recall): 0.026875096257508085
Starting K-Means clustering...
Final number of clusters: 9
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 9
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 6.06392564e-14 -2.59547641e-14 -6.06225887e-09]
 [ 7.28572066e-14 -3.14684240e-14 -6.96017566e-09]
 [ 5.89148507e-14 -2.56488220e-14 -5.72257601e-09]
 ...
 [ 4.65109965e-13 -2.03158032e-13 -4.46118096e-08]
 [ 3.15158693e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7707156375668736
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.038637161254883
..............................Report Parameter...............................
AUCROC: 77.07077184088182
AUCPR: 96.47686756851105
Accuracy: 11.560048805996164
MCC: 0.043641267024559345
F1 score: 0.045740078991912736
PPV (Precision): 0.9918433931484503
TPR (Recall): 0.023409825966425383
Starting K-Means clustering...
Final number of clusters: 11
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 11
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 7.86923139e-15  9.26847695e-09 -7.24118722e-15]
 [ 7.52687804e-15  9.48236377e-09 -6.84327571e-15]
 [ 8.43055318e-15  9.59501223e-09 -6.83456258e-15]
 ...
 [ 4.89974182e-15  7.31287624e-09 -5.34943061e-15]
 [ 5.462991

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7623669148589461
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.024915933609009
..............................Report Parameter...............................
AUCROC: 76.23590098929303
AUCPR: 96.38338006429335
Accuracy: 11.570507233745861
MCC: 0.04377037353635797
F1 score: 0.04596058372197984
PPV (Precision): 0.9918831168831169
TPR (Recall): 0.02352533497612814
Starting K-Means clustering...
Final number of clusters: 15
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 15
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 9.44559150e-11 -3.60988893e-14  6.31421312e-09]
 [ 9.54056986e-11 -3.59178603e-14  6.37777315e-09]
 [ 1.23785093e-10 -4.27792138e-14  8.27507816e-09]
 ...
 [ 7.59673796e-11 -1.92910126e-14  5.08065522e-09]
 [ 8.66474354e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7575731135557877
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.026378631591797
..............................Report Parameter...............................
AUCROC: 75.75652511658902
AUCPR: 96.20120705772068
Accuracy: 11.570507233745861
MCC: 0.04377037353635797
F1 score: 0.04596058372197984
PPV (Precision): 0.9918831168831169
TPR (Recall): 0.02352533497612814
Starting K-Means clustering...
Final number of clusters: 17
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 17
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 2.63107053e-14  6.11412353e-09 -2.07541727e-13]
 [ 2.88772183e-14  6.85076376e-09 -2.29283418e-13]
 [ 2.68412410e-14  6.41562431e-09 -2.12973215e-13]
 ...
 [ 2.50507855e-14  6.00916881e-09 -1.99258942e-13]
 [ 2.46190424e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7455624046969065
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0315310955047607
..............................Report Parameter...............................
AUCROC: 74.55545139229301
AUCPR: 96.19998806916516
Accuracy: 11.580965661495556
MCC: 0.043899136952476527
F1 score: 0.04618103869730359
PPV (Precision): 0.9919224555735057
TPR (Recall): 0.023640843985830894
Starting K-Means clustering...
Final number of clusters: 21
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 21
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-5.91380542e-14  5.50787456e-14 -6.77601263e-09]
 [-5.17423310e-14  4.72339629e-14 -5.89157206e-09]
 [-5.04794489e-14  4.58323031e-14 -5.72486246e-09]
 ...
 [-4.62442147e-14  3.24682408e-14 -5.85273778e-09]
 [-4.796543

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7235327545743924
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0140790939331055
..............................Report Parameter...............................
AUCROC: 72.35249915287716
AUCPR: 95.69001485490702
Accuracy: 11.577479518912323
MCC: 0.04385625375628667
F1 score: 0.04610755923279429
PPV (Precision): 0.9919093851132686
TPR (Recall): 0.023602340982596642
Starting K-Means clustering...
Final number of clusters: 23
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 23
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 5.99709433e-15 -7.13256094e-09  6.38984532e-15]
 [ 6.42643839e-15 -7.02517742e-09  5.82085602e-15]
 [ 6.69705525e-15 -7.87298559e-09  6.92760959e-15]
 ...
 [ 4.22341851e-15 -6.99247225e-09  8.61582461e-16]
 [ 4.7497287

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.7573237878053936
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 2.005927562713623
..............................Report Parameter...............................
AUCROC: 75.73163653687214
AUCPR: 96.10638436327392
Accuracy: 11.570507233745861
MCC: 0.04303574158932243
F1 score: 0.046032342986084995
PPV (Precision): 0.9902912621359223
TPR (Recall): 0.02356383797936239
Starting K-Means clustering...
Final number of clusters: 25
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 25
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[ 1.33200236e-13  1.97252432e-14 -9.19444944e-09]
 [ 1.25557249e-13  1.87524998e-14 -8.74982295e-09]
 [ 1.21948265e-13  1.81268568e-14 -8.46592870e-09]
 ...
 [ 1.23174382e-13  1.75824803e-14 -8.37928453e-09]
 [ 1.24034046e

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.6792195587422424
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.010634660720825
..............................Report Parameter...............................
AUCROC: 67.92136974299181
AUCPR: 94.86945117352819
Accuracy: 12.191040613561094
MCC: 0.047024400592025735
F1 score: 0.05937710060497423
PPV (Precision): 0.9863523573200993
TPR (Recall): 0.030609887571230555
Starting K-Means clustering...
Final number of clusters: 27
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 27
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 3)
W   : d x L = (26, 3)
Complexity of calculate:  [[-1.71369416e-10  2.96388227e-15 -6.41092449e-09]
 [-1.75982336e-10  3.31445882e-15 -6.58348455e-09]
 [-1.74077030e-10  3.12205902e-15 -6.51227841e-09]
 ...
 [-1.65521440e-10  3.01158617e-15 -6.19216490e-09]
 [-1.3704218

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: divide by zero encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability


0.6881904746550327
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 2.0297939777374268
..............................Report Parameter...............................
AUCROC: 68.81834354034278
AUCPR: 95.30281657021158
Accuracy: 11.573993376329092
MCC: 0.04307927322015041
F1 score: 0.046105825279229816
PPV (Precision): 0.9903069466882067
TPR (Recall): 0.023602340982596642
Processing dataset data_BoTIoT.csv with QuantileTransformer scaler ...
..............................Data Overview................................
Train Data Shape: (66929, 27)
Test Data Shape: (28685, 27)
Train Data Labels [0]: [0]
[0. 0. 0. ... 0. 0. 0.]
Number of samples after adding noise: 6359
Number of features: 26
Starting K-Means clustering...
Final number of clusters: 1
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 1
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (

/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.4046516418457031
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 3
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 3
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.4126906394958496
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 5
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 5
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 7.152557373046875e-07
Time test: 1.4092381000518799
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 7
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 7
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.407334566116333
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 9
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 9
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.406205177307129
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 11
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 11
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.4046969413757324
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 13
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 13
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.3975756168365479
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 15
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 15
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.4089200496673584
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 17
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 17
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.4485833644866943
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 19
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 19
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.3965375423431396
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 21
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 21
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.4154777526855469
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 23
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 23
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.4089233875274658
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 25
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 25
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.4056847095489502
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 27
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 27
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 4.76837158203125e-07
Time test: 1.40883207321167
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0
Starting K-Means clustering...
Final number of clusters: 29
Begin calculating NPD --------------
shape of X (26, 6359)
N = 6359   d = 26    c = 29
P_w : d x N = (26, 6359)
P_t : d x N = (26, 6359)
S_w : d x d = (26, 26)
S_t : d x d = (26, 26)
Q   : d x N = (26, 26)
B   : N x L = (26, 0)
W   : d x L = (26, 0)
Complexity of calculate:  []


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421

0.5
...............................Timing Model................................
Time train: 2.384185791015625e-07
Time test: 1.4127967357635498
..............................Report Parameter...............................
AUCROC: 50.0
AUCPR: 90.54209517169252
Accuracy: 9.457904828307477
MCC: 0.0
F1 score: 0.0
PPV (Precision): 0.0
TPR (Recall): 0.0


/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/2354219438.py:182: RuntimeWarning: invalid value encountered in divide
  y_proba[:, 1] = np.minimum(y_score / nu, 1)  # Class 1 probability
/tmp/ipykernel_599143/235421